apiVersion: v1
kind: ConfigMap
metadata:
  name: price-service-config
data:
  CURRENCY_SERVICE_HOST: "currency-service"
  CURRENCY_SERVICE_PORT: "80"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"