/*
 * My test
 * My test description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateRateDto
 */
@JsonPropertyOrder({
  UpdateRateDto.JSON_PROPERTY_RATE_DATE,
  UpdateRateDto.JSON_PROPERTY_CURRENCY
})
@JsonTypeName("UpdateRate")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdateRateDto {
  public static final String JSON_PROPERTY_RATE_DATE = "rateDate";
  private LocalDate rateDate;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private String currency;

  public UpdateRateDto() { 
  }

  public UpdateRateDto rateDate(LocalDate rateDate) {
    
    this.rateDate = rateDate;
    return this;
  }

   /**
   * Get rateDate
   * @return rateDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Fri May 17 03:00:00 MSK 2019", value = "")
  @JsonProperty(JSON_PROPERTY_RATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getRateDate() {
    return rateDate;
  }


  @JsonProperty(JSON_PROPERTY_RATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRateDate(LocalDate rateDate) {
    this.rateDate = rateDate;
  }


  public UpdateRateDto currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateRateDto updateRate = (UpdateRateDto) o;
    return Objects.equals(this.rateDate, updateRate.rateDate) &&
        Objects.equals(this.currency, updateRate.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rateDate, currency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateRateDto {\n");
    sb.append("    rateDate: ").append(toIndentedString(rateDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

